package jtm.activity12;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.stereotype.Component;

import com.mysql.jdbc.Statement;

@Component
public class TeacherManager {

    public static void main(String[] args) {
        System.out.println(new TeacherManager().findTeacher(1));
    }

    protected Connection conn=null;
    protected Statement stmt = null;
    protected ResultSet rs = null;
    protected PreparedStatement prepStat = null;
    
    

    public TeacherManager() {
        /* TODO
		  When new TeacherManager is created, create connection to the database server:
*/
        
        try {    	
         	Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/db?useSSL=false", "root", "Student007");

            conn.setAutoCommit(false); 
            //Use conn.commit() after each Insert/Update/Delete call

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /*
     * Returns a Teacher instance represented by the specified ID.
     */
    public Teacher findTeacher(int id) {
        /*
         TODO
         Execute an SQL statement that searches teacher by ID.
         If teacher is found return Teacher object with values from DB
         If teacher is not found return null */
    	Teacher teacherSelected = new Teacher();
    	try {
    	stmt = (Statement) conn.createStatement();
    	String sql = "select id, firstName, lastName from Teacher where id=?";
    	prepStat = conn.prepareStatement(sql);
    	prepStat.setInt(1, id);
    	ResultSet rs = prepStat.executeQuery();
    	if (rs.first()) {
    		teacherSelected.setId(rs.getInt(1));
    		teacherSelected.setFirstName(rs.getString(2));
    		teacherSelected.setLastName(rs.getString(3));
    	}	else {
    		teacherSelected = null;
    	} 
    	
    	} catch (Exception e) {
    		e.printStackTrace();
    	}

        return teacherSelected;
    }

    /**
     * Returns a list of Teacher objects.
     */
    public List<Teacher> findTeacher(String firstName, String lastName) {
        /* TODO
           Write an sql statement that searches teacher by first and last name and returns results as ArrayList<Teacher>.
           Result list should include all partial results as well, e.g. if first name is matching but last name is not
           still include, the teacher in result list, same applies for lastName
           If nothing is found return empty list! */
    	List<Teacher> teacherList = new ArrayList<Teacher>();
    	Teacher teacher = new Teacher();
    	try {
    	stmt = (Statement) conn.createStatement();
    	String sql = "select id, firstName, lastName from Teacher where firstName=? OR lastName=?";
    	prepStat = conn.prepareStatement(sql);
    	prepStat.setString(1, firstName);
    	prepStat.setString(2, lastName);
    	ResultSet rs = prepStat.executeQuery();
    	while (rs.next()) {
    		teacher = new Teacher(rs.getInt(1),rs.getString(2), rs.getString(3));
    		teacherList.add(teacher);
    	}	 
    	
    	} catch (Exception e) {
    		e.printStackTrace();
    	}
    	
        return teacherList;
    }

    /**
     * Insert an new teacher (first name and last name) into the table.
     */
    public boolean insertTeacher(String firstName, String lastName) {
        /* TODO
           Execute an SQL statement that inserts teacher in database.
           SQL statement should contain only firstName and lastName, ID should be automatically generated by DB */
    	
    	int rowAdded = 0;
    	try {
    	stmt = (Statement) conn.createStatement();
    	String sql = "insert into Teacher (firstName, lastName) values (?,?);";
    	prepStat = conn.prepareStatement(sql);
    	prepStat.setString(1, firstName);
    	prepStat.setString(2, lastName);

    	 rowAdded = prepStat.executeUpdate();

    	conn.commit();
     	} catch (Exception e) {
    		e.printStackTrace();
    	}
    	
    	if (rowAdded > 0) {
    		return true;
    	} else {
    		return false;
    	}
  	
    }
    

    /**
     * Insert teacher object into database
     */
    public boolean insertTeacher(Teacher teacher) {
        /*
        TODO
        Execute an SQL statement that inserts teacher in database.
        SQL statement should contain all fields: id, firstName and lastName
        If teacher is inserted successfully return true, otherwise false */
    	int rowAdded = 0;
    	try {
    	stmt = (Statement) conn.createStatement();
    	String sql = "insert into Teacher (id, firstName, lastName) values (?,?,?);";
    	prepStat = conn.prepareStatement(sql);
    	prepStat.setInt(1, teacher.getId());
    	prepStat.setString(2, teacher.getFirstName());
    	prepStat.setString(3, teacher.getLastName());
    	rowAdded = prepStat.executeUpdate();
    	conn.commit();
     	} catch (Exception e) {
    		e.printStackTrace();
    	}
    	
    	if (rowAdded > 0) {
    		return true;
    	} else {
    		return false;
    	}
  	
    }

    /**
     * Updates an existing Teacher in the repository with the values represented by the Teacher object.
     */
    public boolean updateTeacher(Teacher teacher) {
        /*
            TODO
            Execute an SQL statement that updates teacher information.
            Update teacher in database by it's ID
            If ONE teacher is successfully updated, return true, otherwise false */
    	int rowAdded = 0;
    	try {
    	stmt = (Statement) conn.createStatement();
    	String sql = "update Teacher set firstName=?, lastName=? where id=?;";
    	prepStat = conn.prepareStatement(sql);
    	prepStat.setInt(3, teacher.getId());
    	prepStat.setString(1, teacher.getFirstName());
    	prepStat.setString(2, teacher.getLastName());
    	rowAdded = prepStat.executeUpdate();
    	conn.commit();
     	} catch (Exception e) {
    		e.printStackTrace();
    	}
    	
    	if (rowAdded > 0) {
    		return true;
    	} else {
    		return false;
    	}
  	
    }
    	



    public boolean deleteTeacher(int id) {
        /*
            TODO
            Execute an SQL statement that deletes teacher from database.
            Delete teacher by it's ID
            If one teacher is successfully deleted, return true
            If no teacher is deleted return false */
    	int rowAdded = 0;
    	try {
    	stmt = (Statement) conn.createStatement();
    	String sql = "delete from Teacher where id=?;";
    	prepStat = conn.prepareStatement(sql);
    	prepStat.setInt(1, id);
    	rowAdded = prepStat.executeUpdate();
    	conn.commit();
     	} catch (Exception e) {
    		e.printStackTrace();
    	}
    	
    	if (rowAdded > 0) {
    		return true;
    	} else {
    		return false;
    	}
  	
    }
    public void closeConnection() {
		/*
		 * TODO Close connection to the database server and reset conn object to null
		 */
		try {
			conn.close();
			conn = null;
		} catch (Exception e) {
			e.printStackTrace();
		}
    }
}
